### ISSUE TITLE
入口文件一定得是index.js吗？

### ISSUE THREAD

**Issue by simplecooler** [kenanpengyou/express-webpack-full-live-reload-example#2]
重命名`server/routes/index.js`为`routes.js`就会报错，因为想把`index.js`当做首页的入口，能不能支持自定义文件名。然后把`client`下面的`page1`和`page2`重命名为`index`和`users`之后，输入`npm run build`之后`public`文件夹里对应的只有`bundle.js`，对应的css文件没有了。

**Comment by simplecooler** [comment]
没有css的解决了，一定要先`npm run production`一次才会出来

**Comment by kenanpengyou** [comment]
@simplecooler  在`app.js`里和Express路由设置有关的是`require('./server/routes')(app);`。 默认的`index.js`和这个写法是对应的。 如果想要修改为`server/routes/routes.js`，这里也要改为`require('./server/routes/routes')(app);`。

另一个问题，`page1`和`page2`是一个示例命名，请注意`webpack.config.js`里的`entry`的内容，如果更改了`client`下的入口文件所在目录，`webpack.config.js`也应该对应修改，否则应该是找不到入口文件不会有任何输出。你的`bundle.js`可能是之前就在`public`里未删除的。

**Comment by simplecooler** [comment]
谢谢，这些问题都解决了。
