### ISSUE TITLE
`npm install jquery --save`安装的jquery如何引入到项目中呢？

### ISSUE THREAD

**Issue by simplecooler** [kenanpengyou/express-webpack-full-live-reload-example#3]
在`commom.js`中`require("node_modules/jquery/dist.jquery.js");`会报错

**Comment by kenanpengyou** [comment]
@simplecooler  直接用 `var $ = require("jquery");`

**Comment by simplecooler** [comment]
这样引入之后，在各页面中的js文件里使用`$`会报`ReferenceError: Can't find variable: $`，感觉没有全局引入，而且这样引入`jquery`之后跑`npm run production`会有两个`warning`。

**Comment by kenanpengyou** [comment]
@simplecooler  常规的CommonJs风格的用法是任何时候需要用到`jquery`，都`require()`一次。 不过，全局准备好`jquery`可以更方便。推荐的做法是在webpack的配置文件的`plugins`增加以下内容：

~~~javascript
new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery'
}),
~~~

表示把`require('jquery')`的内容作为所有bundle module共用的内容，输出为`$`和`jQuery`两个变量。

**Comment by simplecooler** [comment]
谢谢帮助，现在终于都理顺了，开发流很不错。
