### ISSUE TITLE
 ERROR in Cannot find module 'node-sass'

### ISSUE THREAD

**Issue by allanruin** [kenanpengyou/express-webpack-full-live-reload-example#4]
关键报错信息类似

> ERROR in Cannot find module 'node-sass'
>@ ./client/page1/index.scss 4:14-191 13:2-17:4 14:20-197
> ERROR in Cannot find module 'node-sass'
> @ ./client/page2/index.scss 4:14-191 13:2-17:4 14:20-197

于是执行 `npm install node-sass`,报错，

```
>node-sass@3.9.3 install /root/projects/vm/node_modules/node-sass
>node scripts/install.js
sh: 1: node: Permission denied
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/root/software/node/bin/node" "/root/software/node/bin/npm" "install" "node-sass"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
```

于是使用
```
# npm config set unsafe-perm true 
# npm install node-sass -g
```

安装完毕后，再次执行npm start
错误依旧。。

请教可能是什么问题引起的呢？

**Comment by kenanpengyou** [comment]
@allanruin  我原来也碰到过很多次这个`node-sass`的npm包的无法成功安装或安装后有错误的问题。

像你这样碰到它问题，可以考虑之前的旧版，比如修改`package.json`里的依赖为：

~~~json
"node-sass": "^3.4.2"
~~~

这是我最近更新前的旧版，可能更稳定可用。

你也可以到[node-sass的issue](https://github.com/sass/node-sass/issues)咨询下。

**Comment by allanruin** [comment]
@kenanpengyou 改了版本可以了。
实际安装的是`node-sass@3.9.3 node_modules/node-sass`版本。感谢回复。很久不写前端，不太了解整个生态，我就不去报issue了。
