### ISSUE TITLE
关于“适时刷新”的不解

### ISSUE THREAD

**Issue by uojo** [kenanpengyou/express-webpack-full-live-reload-example#6]
我执行 npm run 后，修改了 server 下 page 视图，结果过了 大概10秒后就刷新了一次页面，且之后是每隔 10秒的样子就会刷新一次。不知是作者所设想了效果吗？
我的设想效果如下：
当 server 端page视图发生变更后，过个1-2秒刷新一次浏览器，之后就不用再定时刷新了吧！

**Comment by uojo** [comment]
解决了，我node版本是 5.10，我升级到 6.2，就正常了

**Comment by kenanpengyou** [comment]
@uojo 原来如此。 这个项目最初创建的时候是 Node 4.x LTS， 现在以Node官方网站给的信息来看，已经是 6.x LTS了。
