### ISSUE TITLE
IE8下运行报JS错误，无法调试

### ISSUE THREAD

**Issue by crazyliuzc** [kenanpengyou/express-webpack-full-live-reload-example#7]
大神，如果我想发布生产环境，不需要实时刷新，考虑兼容，需要什么命令启动

**Comment by kenanpengyou** [comment]
@crazyliuzc   <del>内容和标题不符系列</del>

受限于webpack-hot-middleware这些库的要求，IE的低版本的确是不可用的。你可以考虑[webpack-hot-middleware-ie8](https://www.npmjs.com/package/webpack-hot-middleware-ie8)。

发布生产环境使用`npm run production`。我测试了下，这种状态下，IE8是可以正常浏览的。

**Comment by crazyliuzc** [comment]
@kenanpengyou 多谢大神
