### ISSUE TITLE
在page1和page2页面添加<a>标签用以跳转，在非production模式启动下会很卡

### ISSUE THREAD

**Issue by crazyliuzc** [kenanpengyou/express-webpack-full-live-reload-example#8]
![image](https://cloud.githubusercontent.com/assets/6993730/21893266/5f84857e-d915-11e6-80f7-4aa232862b5b.png)

![image](https://cloud.githubusercontent.com/assets/6993730/21893286/6e7388a0-d915-11e6-87c3-e7de3c6eccbd.png)

大神帮忙再瞧瞧

**Comment by kenanpengyou** [comment]
@crazyliuzc   测试了，加入链接以及相互跳转并没有影响，各自仍然可以修改后刷新，没有看到卡一类的现象。  你这边的卡（最好描述再具体一点）可能是其他原因引起的。

**Comment by crazyliuzc** [comment]
额，感觉出现幻觉了，现在测试重现不了，昨天测试还是有点卡的，npm start最卡，难道是那时候我电脑卡了
