### ISSUE TITLE
Module not found: Error: Can't resolve './client/home'

### ISSUE THREAD

**Issue by stayby** [kenanpengyou/express-webpack-full-live-reload-example#9]
错误信息如下：
ERROR in multi ./client/home webpack-hot-middleware/client?reload=true
Module not found: Error: Can't resolve './client/home' in 'D:\Demos\express-demo\express-webpack'
 @ multi ./client/home webpack-hot-middleware/client?reload=true

**Comment by stayby** [comment]
找到原因了
./client/home下的入口文件应该是index.js，否则就要在entry里指定文件名，比如:
entry:{
	home:['./client/home/home.js',hotMiddlewareScript]
}
另外,升级到webpack2 后，所有的loader 后面都要写上 '-loader'
萌新一只，见笑了

**Comment by kenanpengyou** [comment]
@stayby  没关系的，解决就好。 `index.js`算是一个比较取巧的命名，对应的入口地址可以只写到目录。

感谢提醒，我之后更新一版webpack2，原来的webpack1留在另一个分支上。
